import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

import NavigationHeader from "@/components/header";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Portfolio - Vitor Henrique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} font-ubuntu antialiased`}>
        <NavigationHeader />
        {children}
      </body>
    </html>
  );
}
